import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import styles from '../styles/Home.module.css'

export default function Home() {
  return (

    <div className={styles.container}>
     
      <Head>
        <title>Hisam Nasir</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
      
        <div className={styles.imgwrap}>
        <span className='header-image'><Image className={styles.myImg} src='/homeimg.png' layout='fill' alt="dak"/></span>
        <h1 className={styles.title}>
           React Based Article
        </h1>

        <p className={styles.description}>
         A project by Hisam made in Next.js (framework)
        </p>
        </div>
        
        <h2 className={styles.polularBlog}>Popular Blogs</h2>
<div className={styles.popular}>
  
<div className={styles.blogs}>
          
          <div className={styles.blogitem}>
            <h3>How to learn JavaScript in 2022?</h3>
          </div>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum 
            eveniet, nulla sed ipsam ex amet, molestiae placeat blanditiis, 
            aliquid deserunt mollitia quae eum aperiam quis velit itaque ipsum
             nobis! Laboriosam.
          </p>
        </div>

        <div className={styles.blogs}>
          
          <div className={styles.blogitem}>
            <h3>How to learn JavaScript in 2022?</h3>
          </div>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum 
            eveniet, nulla sed ipsam ex amet, molestiae placeat blanditiis, 
            aliquid deserunt mollitia quae eum aperiam quis velit itaque ipsum
             nobis! Laboriosam.
          </p>
        </div>

        <div className={styles.blogs}>
          
          <div className={styles.blogitem}>
            <h3>How to learn JavaScript in 2022?</h3>
          </div>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum 
            eveniet, nulla sed ipsam ex amet, molestiae placeat blanditiis, 
            aliquid deserunt mollitia quae eum aperiam quis velit itaque ipsum
             nobis! Laboriosam.
          </p>
        </div>

</div>

      </main>

    </div>
  )
}
